export type OrganicProfile = {
  id: number;
  platform: "tiktok" | "instagram";
  customLabel: string;
  profileUrl: string;
  platformUserId: string | null;
  username: string | null;
  displayName: string | null;
  bio: string | null;
  bioLink: string | null;
  avatarUrl: string | null;
  isVerified: boolean | null;
  followerCount: number | null;
  totalPosts: number | null;
  trackingStatus: "Not Initialized" | "Processing" | "Active" | "Error" | "Paused";
  lastScrapedAt: string | null;
  profileUpdatedAt: string | null;
  newestPostDate: string | null;
  createdAt: string;
  postCount?: number;
};

export type OrganicPost = {
  id: number;
  platform: "tiktok" | "instagram";
  postId: string;
  profileRef: number;
  username: string;
  postUrl: string;
  publishDate: string;
  contentType: "Video" | "Carousel";
  caption: string | null;
  coverUrl: string;
  videoUrl: string | null;
  videoDuration: number | null;
  slideImages: string | null;
  slideCount: number;
  hashtags: string | null;
  musicName: string | null;
  musicAuthor: string | null;
  musicIsOriginal: boolean | null;
  likes: number;
  comments: number;
  views: number;
  shares: number | null;
  saves: number | null;
  contentAngle: string | null;
  contentMechanic: string | null;
  targetViewer: string | null;
  valueProp: string | null;
  openingHook: string | null;
  visualHook: string | null;
  contentStructure: string | null;
  retentionDriver: string | null;
  outroCta: string | null;
  fullTranscript: string | null;
  aiAnalysisStatus: "Complete" | "Error";
  aiErrorMessage: string | null;
  aiLastAnalyzedAt: string | null;
  ingestedAt: string;
};
